spring:
  application:
    name: wen-api-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wen_api # 自己数据库地址
    username: root # 自己数据库用户名
    password: 123456 # 自己数据库密码
  session:
    timeout: 86400
  # 配置Redis
  data:
    redis:
      port: 6379
      host: localhost
      database: 1
      timeout: # PT2H30M 设置session的过期时间为2h30min

# 配置端口号和全局访问路径
server:
  port: 8082
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
  address: 0.0.0.0

# 配置 Dubbo 的应用名、Dubbo 协议信息、Dubbo 使用的注册中心地址
dubbo:
  application:
    name: dubbo-wen-api-backend
    qos-port: 22222
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html # 用于 swagger-ui HTML 文档的自定义路径。
    tags-sorter: alpha # 对每个API的操作列表进行排序。
    operations-sorter: alpha # 对每个 API 的标签列表进行排序。
  api-docs:
    path: /v3/api-docs # 对于 Json 格式的 OpenAPI 文档的自定义路径
  group-configs:
    - group: 'wen-api'
      paths-to-match: '/**'
      packages-to-scan: com.wen.wenapiproject.controller # 修改为自己的controller包路径

# knife4j的增强配置，不需要增强可以不配
knife4j:
  # 开启生产环境屏蔽(线上环境的时候再开启)
  production: false
  # 开启增强配置
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  configuration:
    # 就是这行代码让mybatis可以输出sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 自定义 starter 配置
wen:
  api:
    client:
      access-key: wen-api
      secret-key: admin
