server:
  port: 8090
spring:
  application:
    name: wen-api-gateway
  devtools:
    livereload:
      port: 35749
  cloud:
    gateway:
      routes:
        - id: wen_api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
