server:
  port: 8090
spring:
  application:
    name: wen-api-gateway
  devtools:
    livereload:
      port: 35749
  cloud:
    gateway:
      routes:
        - id: wen_api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**

# 配置 Dubbo 的应用名、Dubbo 协议信息、Dubbo 使用的注册中心地址
dubbo:
  application:
    name: dubbo-wen-api-gateway
    qos-port: 33333
  protocol:
    name: dubbo
    port: 50050
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181